// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WorkWave.Workwave.Mobile.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Payments")]
    [NUnit.Framework.CategoryAttribute("Payments")]
    public partial class PaymentsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Payments.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Payments", null, ProgrammingLanguage.CSharp, new string[] {
                        "Payments"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cash Payment")]
        public virtual void CashPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cash Payment", null, ((string[])(null)));
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Email",
                        "mdelgoda+qa@workwave.com"});
            table1.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 7
 testRunner.When("I Login", ((string)(null)), table1, "When ");
#line 11
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 12
 testRunner.Given("Not Started Order Opened", ((string)(null)), table2, "Given ");
#line 15
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "PaymentType",
                        "Cash"});
            table3.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
#line 17
 testRunner.When("Payment Made", ((string)(null)), table3, "When ");
#line 21
 testRunner.When("Process Payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Payment")]
        public virtual void CheckPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Payment", null, ((string[])(null)));
#line 25
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Email",
                        "mdelgoda+qa@workwave.com"});
            table4.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 27
 testRunner.When("I Login", ((string)(null)), table4, "When ");
#line 31
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 32
 testRunner.Given("Not Started Order Opened", ((string)(null)), table5, "Given ");
#line 35
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 36
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "PaymentType",
                        "Check"});
            table6.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
#line 37
 testRunner.When("Payment Made", ((string)(null)), table6, "When ");
#line 41
 testRunner.When("Process Payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Credit Card Payment → No Payment Processor")]
        public virtual void CreditCardPaymentNoPaymentProcessor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Credit Card Payment → No Payment Processor", null, ((string[])(null)));
#line 45
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 46
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Email",
                        "mdelgoda+qa@workwave.com"});
            table7.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 47
 testRunner.When("I Login", ((string)(null)), table7, "When ");
#line 51
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 52
 testRunner.Given("Not Started Order Opened", ((string)(null)), table8, "Given ");
#line 55
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table9.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
#line 57
 testRunner.When("Payment Made", ((string)(null)), table9, "When ");
#line 61
 testRunner.When("Process Payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Record Credit Card Payment,and Store Card,with Stored Card → Vantiv")]
        public virtual void RecordCreditCardPaymentAndStoreCardWithStoredCardVantiv()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Record Credit Card Payment,and Store Card,with Stored Card → Vantiv", null, ((string[])(null)));
#line 65
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 66
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Email",
                        "mdelgoda+emp5@workwave.com"});
            table10.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 67
 testRunner.When("I Login", ((string)(null)), table10, "When ");
#line 71
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 72
 testRunner.Given("Not Started Order Opened", ((string)(null)), table11, "Given ");
#line 75
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table12.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table12.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table12.AddRow(new string[] {
                        "SaveOption",
                        "No"});
            table12.AddRow(new string[] {
                        "CardNumber",
                        "6011000990139424"});
            table12.AddRow(new string[] {
                        "CVV",
                        "1234"});
            table12.AddRow(new string[] {
                        "PaymentAmount",
                        "1.00"});
#line 77
 testRunner.When("Select Payment Mode", ((string)(null)), table12, "When ");
#line 86
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table13.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table13.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table13.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table13.AddRow(new string[] {
                        "CardNumber",
                        "6011000990139424"});
            table13.AddRow(new string[] {
                        "CVV",
                        "1234"});
            table13.AddRow(new string[] {
                        "PaymentAmount",
                        "1.00"});
#line 88
 testRunner.When("Select Payment Mode", ((string)(null)), table13, "When ");
#line 97
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 98
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table14.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table14.AddRow(new string[] {
                        "Option",
                        "Visa - 1111 (12/25)"});
            table14.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table14.AddRow(new string[] {
                        "CardNumber",
                        "6011000990139424"});
            table14.AddRow(new string[] {
                        "CVV",
                        "1234"});
            table14.AddRow(new string[] {
                        "PaymentAmount",
                        "1.00"});
#line 99
 testRunner.When("Select Payment Mode", ((string)(null)), table14, "When ");
#line 108
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Record Credit Card Payment,and Store Card,with Stored Card → OpenEdge")]
        public virtual void RecordCreditCardPaymentAndStoreCardWithStoredCardOpenEdge()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Record Credit Card Payment,and Store Card,with Stored Card → OpenEdge", null, ((string[])(null)));
#line 112
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 113
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table15.AddRow(new string[] {
                        "Email",
                        "mdelgoda+emp1@workwave.com"});
            table15.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 114
 testRunner.When("I Login", ((string)(null)), table15, "When ");
#line 118
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table16.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 119
 testRunner.Given("Not Started Order Opened", ((string)(null)), table16, "Given ");
#line 122
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 123
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table17.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table17.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table17.AddRow(new string[] {
                        "SaveOption",
                        "No"});
            table17.AddRow(new string[] {
                        "CardNumber",
                        "5413330089604111"});
            table17.AddRow(new string[] {
                        "CVV",
                        "123"});
            table17.AddRow(new string[] {
                        "PaymentAmount",
                        "13.17"});
#line 124
 testRunner.When("Select Payment Mode OpenEdge", ((string)(null)), table17, "When ");
#line 133
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table18.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table18.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table18.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table18.AddRow(new string[] {
                        "CardNumber",
                        "5413330089604111"});
            table18.AddRow(new string[] {
                        "CVV",
                        "123"});
            table18.AddRow(new string[] {
                        "PaymentAmount",
                        "13.17"});
#line 135
 testRunner.When("Select Payment Mode OpenEdge", ((string)(null)), table18, "When ");
#line 144
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 145
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table19.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table19.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table19.AddRow(new string[] {
                        "Option",
                        "Visa - 0010 (12/25)"});
            table19.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table19.AddRow(new string[] {
                        "CardNumber",
                        "5413330089604111"});
            table19.AddRow(new string[] {
                        "CVV",
                        "123"});
            table19.AddRow(new string[] {
                        "PaymentAmount",
                        "13.17"});
#line 146
 testRunner.When("Select Payment Mode OpenEdge", ((string)(null)), table19, "When ");
#line 155
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Record Credit Card Payment,and Store Card,with Stored Card → WorkWave Payments")]
        public virtual void RecordCreditCardPaymentAndStoreCardWithStoredCardWorkWavePayments()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Record Credit Card Payment,and Store Card,with Stored Card → WorkWave Payments", null, ((string[])(null)));
#line 158
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 159
 testRunner.Given("Logged Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "Email",
                        "mdelgoda+emp2@workwave.com"});
            table20.AddRow(new string[] {
                        "Password",
                        "WorkWave1!"});
#line 160
 testRunner.When("I Login", ((string)(null)), table20, "When ");
#line 164
 testRunner.Then("Verify logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table21.AddRow(new string[] {
                        "DetailsNeeded",
                        "false"});
#line 165
 testRunner.Given("Not Started Order Opened", ((string)(null)), table21, "Given ");
#line 168
 testRunner.When("Navigate To Payment View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 169
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table22.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table22.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table22.AddRow(new string[] {
                        "SaveOption",
                        "No"});
            table22.AddRow(new string[] {
                        "CardNumber",
                        "5413330089010681"});
            table22.AddRow(new string[] {
                        "CVV",
                        "123"});
            table22.AddRow(new string[] {
                        "PaymentAmount",
                        "43.17"});
#line 170
 testRunner.When("Select Payment Mode WWP", ((string)(null)), table22, "When ");
#line 179
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 180
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table23.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table23.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table23.AddRow(new string[] {
                        "Option",
                        "Enter a new card.."});
            table23.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table23.AddRow(new string[] {
                        "CardNumber",
                        "5413330089010681"});
            table23.AddRow(new string[] {
                        "CVV",
                        "123"});
            table23.AddRow(new string[] {
                        "PaymentAmount",
                        "43.17"});
#line 181
 testRunner.When("Select Payment Mode WWP", ((string)(null)), table23, "When ");
#line 190
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
 testRunner.Given("Payments Opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "PaymentType",
                        "Credit Card"});
            table24.AddRow(new string[] {
                        "PayTotalDue",
                        "true"});
            table24.AddRow(new string[] {
                        "Option",
                        "Visa - 0006 (12/25)"});
            table24.AddRow(new string[] {
                        "SaveOption",
                        "Yes"});
            table24.AddRow(new string[] {
                        "CardNumber",
                        "5413330089010681"});
            table24.AddRow(new string[] {
                        "CVV",
                        "123"});
            table24.AddRow(new string[] {
                        "PaymentAmount",
                        "43.17"});
#line 192
 testRunner.When("Select Payment Mode WWP", ((string)(null)), table24, "When ");
#line 201
 testRunner.Then("Verify Payment Made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

